vim.opt.spell = true
vim.opt.spelllang = 'en_us'

vim.cmd { cmd = 'cnoreabbrev', args = {'Q!', 'q!'} }
vim.cmd { cmd = 'cnoreabbrev', args = {'W!', 'w!'} }
vim.cmd { cmd = 'cnoreabbrev', args = {'Q!', 'q!'} }
vim.cmd { cmd = 'cnoreabbrev', args = {'Q1', 'q!'} }
vim.cmd { cmd = 'cnoreabbrev', args = {'Qall!', 'qall!'} }
vim.cmd { cmd = 'cnoreabbrev', args = {'Wq', 'wq'} }
vim.cmd { cmd = 'cnoreabbrev', args = {'Wa', 'wa'} }
vim.cmd { cmd = 'cnoreabbrev', args = {'wQ', 'wq'} }
vim.cmd { cmd = 'cnoreabbrev', args = {'WQ', 'wq'} }
vim.cmd { cmd = 'cnoreabbrev', args = {'qw', 'wq'} }
vim.cmd { cmd = 'cnoreabbrev', args = {'W', 'w'} }
vim.cmd { cmd = 'cnoreabbrev', args = {'Q', 'q'} }
vim.cmd { cmd = 'cnoreabbrev', args = {'Qall', 'qall'} }

vim.cmd { cmd = 'iabbrev', args = {'Flase', 'False'} }
vim.cmd { cmd = 'iabbrev', args = {'Ture', 'True'} }
vim.cmd { cmd = 'iabbrev', args = {'abrot', 'abort'} }
vim.cmd { cmd = 'iabbrev', args = {'acutal', 'actual'} }
vim.cmd { cmd = 'iabbrev', args = {'amin', 'main'} }
vim.cmd { cmd = 'iabbrev', args = {'breka', 'break'} }
vim.cmd { cmd = 'iabbrev', args = {'calss', 'class'} }
vim.cmd { cmd = 'iabbrev', args = {'cavnas', 'canvas'} }
vim.cmd { cmd = 'iabbrev', args = {'cosnt', 'const'} }
vim.cmd { cmd = 'iabbrev', args = {'ednl', 'endl'} }
vim.cmd { cmd = 'iabbrev', args = {'exprot', 'export'} }
vim.cmd { cmd = 'iabbrev', args = {'exprots', 'exports'} }
vim.cmd { cmd = 'iabbrev', args = {'firend', 'friend'} }
vim.cmd { cmd = 'iabbrev', args = {'flase', 'false'} }
vim.cmd { cmd = 'iabbrev', args = {'fucntion', 'function'} }
vim.cmd { cmd = 'iabbrev', args = {'funciton', 'function'} }
vim.cmd { cmd = 'iabbrev', args = {'futrue', 'future'} }
vim.cmd { cmd = 'iabbrev', args = {'heigth', 'height'} }
vim.cmd { cmd = 'iabbrev', args = {'imoprt', 'import'} }
vim.cmd { cmd = 'iabbrev', args = {'imporve', 'improve'} }
vim.cmd { cmd = 'iabbrev', args = {'improt', 'import'} }
vim.cmd { cmd = 'iabbrev', args = {'incldue', 'include'} }
vim.cmd { cmd = 'iabbrev', args = {'inlcude', 'include'} }
vim.cmd { cmd = 'iabbrev', args = {'ipmort', 'import'} }
vim.cmd { cmd = 'iabbrev', args = {'itme', 'item'} }
vim.cmd { cmd = 'iabbrev', args = {'itmes', 'items'} }
vim.cmd { cmd = 'iabbrev', args = {'lnog', 'long'} }
vim.cmd { cmd = 'iabbrev', args = {'namepsace', 'namespace'} }
vim.cmd { cmd = 'iabbrev', args = {'paht', 'path'} }
vim.cmd { cmd = 'iabbrev', args = {'pakcage', 'package'} }
vim.cmd { cmd = 'iabbrev', args = {'pakcages', 'packages'} }
vim.cmd { cmd = 'iabbrev', args = {'paylaod', 'payload'} }
vim.cmd { cmd = 'iabbrev', args = {'priavte', 'private'} }
vim.cmd { cmd = 'iabbrev', args = {'pyaload', 'payload'} }
vim.cmd { cmd = 'iabbrev', args = {'reqeust', 'request'} }
vim.cmd { cmd = 'iabbrev', args = {'requrie', 'require'} }
vim.cmd { cmd = 'iabbrev', args = {'retrun', 'return'} }
vim.cmd { cmd = 'iabbrev', args = {'reutrn', 'return'} }
vim.cmd { cmd = 'iabbrev', args = {'riase', 'raise'} }
vim.cmd { cmd = 'iabbrev', args = {'rnage', 'range'} }
vim.cmd { cmd = 'iabbrev', args = {'sefl', 'self'} }
vim.cmd { cmd = 'iabbrev', args = {'slef', 'self'} }
vim.cmd { cmd = 'iabbrev', args = {'ture', 'true'} }
vim.cmd { cmd = 'iabbrev', args = {'virutal', 'virtual'} }
vim.cmd { cmd = 'iabbrev', args = {'vodi', 'void'} }
vim.cmd { cmd = 'iabbrev', args = {'wdith', 'width'} }
vim.cmd { cmd = 'iabbrev', args = {'whiel', 'while'} }
vim.cmd { cmd = 'iabbrev', args = {'widht', 'width'} }
vim.cmd { cmd = 'iabbrev', args = {'yeild', 'yield'} }
