#!/bin/bash
# @Copyright (c) 2018 Xvezda <https://xvezda.com>
# @Description: backup script for dotfiles

# Get script's path
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
cd $DIR

# Create path
BACKUP_DIRS=("vim" "tmux" "brew" "zsh" "tidy")
for p in "${BACKUP_DIRS[@]}"
do
    mkdir -p src/$p
done

# Backup vim dotfiles
cp -R $HOME/.vim/private src/vim/
cp -R $HOME/.vim/syntax src/vim/
cp -R $HOME/.vim/UltiSnips src/vim/
cp $HOME/.vimrc src/vim/vimrc
cp $HOME/.vimrc.local src/vim/vimrc.local
cp $HOME/.vimrc.local.bundles src/vim/vimrc.local.bundles

# Backup tmux dotfiles
cp $HOME/.tmux.conf src/tmux/tmux.conf
cp $(ls $HOME/.tmux/*.conf) src/tmux/

# Backup brew dotfiles
which brew && brew bundle dump && mv $PWD/Brewfile src/brew

# Backup zsh dotfiles
cp $HOME/.zshrc src/zsh/zshrc
cp $HOME/.zprofile src/zsh/zprofile

# Backup tidy configuration
cp $HOME/.tidyrc src/tidy/tidyrc

# Backup pip requirements
which pip && pip freeze > src/pip/requirements.txt
which pip3 && pip3 freeze > src/pip/py3-requirements.txt


# ft:vim=sh
