#!/usr/bin/env bash
# @Copyright (c) 2018 Xvezda <https://xvezda.com>
# @Description: backup script for dotfiles

# Get script's path
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
cd $DIR

# Create path
BACKUP_DIRS=("git" "vim" "tmux" "brew" "zsh" "bash")
for p in "${BACKUP_DIRS[@]}"
do
    mkdir -p src/$p
done

if type git &>/dev/null; then
    echo "[*] Backup git dotfiles"
    test -f $HOME/.gitignore && cp $HOME/.gitignore src/git/gitignore
fi

if type vim &>/dev/null; then
    echo "[*] Backup vim dotfiles"
    cp -R $HOME/.vim/private src/vim/
    cp -R $HOME/.vim/syntax src/vim/
    cp -R $HOME/.vim/UltiSnips src/vim/
    cp $HOME/.vimrc src/vim/vimrc
    cp $HOME/.vimrc.local src/vim/vimrc.local
    cp $HOME/.vimrc.local.bundles src/vim/vimrc.local.bundles
fi

if type nvim &>/dev/null; then
    echo "[*] Backup nvim dotfiles"
    cp -R $HOME/.config/nvim src/
fi

if type tmux &>/dev/null; then
    echo "[*] Backup tmux dotfiles"
    cp $HOME/.tmux.conf src/tmux/tmux.conf
    cp $(ls $HOME/.tmux/*.conf) src/tmux/
fi

if type brew &>/dev/null; then
    echo "[*] Backup brew dotfiles"
    brew bundle dump && mv $PWD/Brewfile src/brew
fi

if type bash > /dev/null 2>&1; then
    echo "[*] Backup bash dotfiles"
    for file in ".bashrc" ".bash_profile"; do
        if [ -f "$HOME/$file" ]; then
            cp "$HOME/$file" "src/bash/${file#.}"
        fi
    done
fi

if type zsh &>/dev/null 2>&1; then
    echo "[*] Backup zsh dotfiles"
    cp $HOME/.zshrc src/zsh/zshrc
    cp $HOME/.zprofile src/zsh/zprofile

    # Backup oh my zsh files
    if [ -e "$HOME/.oh-my-zsh" ]; then
        mkdir -p src/zsh/custom
        cp -R $HOME/.oh-my-zsh/custom/themes src/zsh/custom/
        find $HOME/.oh-my-zsh/custom/plugins -mindepth 1 -maxdepth 1 -type d \
            | while read fp; do \
            if [ -d "$fp/.git" ]; then \
                git submodule --quiet add --force \
                    $(cd "$fp" && git remote get-url origin) \
                    src/zsh/custom/plugins/$(basename $fp) \
            else cp -R "$fp" src/zsh/custom/plugins/; fi; done
    fi
fi

# On windows
if [ "$XVZD_OSTYPE" = "windows" ]
then
    echo "[*] Backup windows terminal profiles"
    mkdir -p src/wt
    PROFILES_PATH=$(wslpath $USERPROFILE)/AppData/Local/Packages/Microsoft.WindowsTerminal_*/LocalState/profiles.json
    test -e ${PROFILES_PATH[0]} && cp ${PROFILES_PATH[0]} src/wt/profiles.json
    unset PROFILES_PATH
fi

echo "[+] Success backup!"


# ft:vim=sh
