#!/usr/bin/env bash
# Copyright (c) 2018 Xvezda <https://xvezda.com>
# author:   xvezda <xvezda@naver.com>
# desc:     install dotfiles


# Get current absolute path
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
cd $DIR


# Vim dotfiles setup
function vimconf_setup() {
    # Install vim configurations
    which vim > /dev/null 2>&1 || return 0

    # Move configuration files to home directory
    VIMDOT_PATH="$DIR/src/vim"
    mkdir -p $HOME/.vim/private
    mkdir -p $HOME/.vim/syntax
    mkdir -p $HOME/.vim/UltiSnips
    cp -R $VIMDOT_PATH/private/* $HOME/.vim/private
    cp -R $VIMDOT_PATH/syntax/* $HOME/.vim/syntax
    cp -R $VIMDOT_PATH/UltiSnips/* $HOME/.vim/UltiSnips
    cp $VIMDOT_PATH/vimrc $HOME/.vimrc
    cp $VIMDOT_PATH/vimrc.local $HOME/.vimrc.local
    cp $VIMDOT_PATH/vimrc.local.bundles $HOME/.vimrc.local.bundles

    # Install vim plugins
    vim -es +'silent! PlugInstall' +qall
}


# NeoVim dotfiles setup
function nvimconf_setup() {
    # Install nvim configurations
    which nvim > /dev/null 2>&1 || return 0

    # Move configuration files to home directory
    VIMDOT_PATH="$DIR/src/vim"
    mkdir -p $XDG_CONFIG_HOME/nvim/private
    mkdir -p $XDG_CONFIG_HOME/nvim/syntax
    mkdir -p $XDG_CONFIG_HOME/nvim/UltiSnips
    cp -R $VIMDOT_PATH/private/* $XDG_CONFIG_HOME/nvim/private
    cp -R $VIMDOT_PATH/UltiSnips/* $XDG_CONFIG_HOME/nvim/UltiSnips
    cp $VIMDOT_PATH/vimrc $XDG_CONFIG_HOME/nvim/init.vim
    cp $VIMDOT_PATH/vimrc.local $XDG_CONFIG_HOME/nvim/local_init.vim
    cp $VIMDOT_PATH/vimrc.local.bundles $XDG_CONFIG_HOME/nvim/local_bundles.vim

    test -d $HOME/.vim || ln -s $XDG_CONFIG_HOME/nvim $HOME/.vim
    test -f $HOME/.vimrc || ln -s $XDG_CONFIG_HOME/nvim/init.vim $HOME/.vimrc
    test -f $HOME/.vimrc.local || ln -s $XDG_CONFIG_HOME/nvim/local_init.vim $HOME/.vimrc.local
    test -f $HOME/.vimrc.local.bundles || ln -s $XDG_CONFIG_HOME/nvim/local_bundles.vim $HOME/.vimrc.local.bundles

    # Install vim plugins
    nvim -es +'silent! PlugInstall' +qall
}


# Tmux dotfiles setup
function tmuxconf_setup() {
    # Install tmux configurations
    which tmux > /dev/null 2>&1 || return 0

    # Create tmux local settings directory
    mkdir -p $HOME/.tmux

    # Move tmux configuration files to home directory
    TMUXDOT_PATH="$DIR/src/tmux"
    cp $TMUXDOT_PATH/tmux.conf $HOME/.tmux.conf

    cp $TMUXDOT_PATH/jellybeans.conf $HOME/.tmux/jellybeans.conf
    cp $TMUXDOT_PATH/tmux.local.conf $HOME/.tmux/tmux.local.conf
    cp $TMUXDOT_PATH/key.conf $HOME/.tmux/key.conf

    # Backward compatibility
    cp $TMUXDOT_PATH/jellybeans.old.conf $HOME/.tmux/jellybeans.old.conf
    cp $TMUXDOT_PATH/tmux.local.old.conf $HOME/.tmux/tmux.local.old.conf
    cp $TMUXDOT_PATH/key.old.conf $HOME/.tmux/key.old.conf

    # Reload tmux configuration
    if [ -n "$TMUX" ]
    then
        tmux source-file $HOME/.tmux.conf > /dev/null
    else
        tmux start-server \; source-file $HOME/.tmux.conf > /dev/null
    fi
}


# Bash dotfiles setup
function bashconf_setup() {
    which bash > /dev/null 2>&1 || return 0
    BASHDOT_PATH="$DIR/src/bash"

    cp $BASHDOT_PATH/bashrc $HOME/.bashrc
    cp $BASHDOT_PATH/bash_profile $HOME/.bash_profile
}

# Zsh dotfiles setup
function zshconf_setup() {
    which zsh > /dev/null 2>&1 || return 0
    ZSHDOT_PATH="$DIR/src/zsh"

    cp $ZSHDOT_PATH/zprofile $HOME/.zprofile
    cp $ZSHDOT_PATH/zshrc $HOME/.zshrc

    if [ -e $HOME/.oh-my-zsh ]; then
        git submodule init $ZSHDOT_PATH && git submodule update
        cp -R $ZSHDOT_PATH/custom/* $HOME/.oh-my-zsh/custom >/dev/null 2>&1

        if [ ! -e $HOME/.zsh ]; then
            mkdir -p $HOME/.zsh
            git clone --depth=1 \
                https://github.com/romkatv/gitstatus.git $HOME/.zsh/gitstatus

        fi
    fi
}


function tidyconf_setup() {
    which tidy > /dev/null 2>&1 || return 0
    TIDYDOT_PATH="$DIR/src/tidy"

    cp $TIDYDOT_PATH/tidyrc $HOME/.tidyrc
}


function gitconf_setup() {
    GITDOT_PATH="$DIR/src/git"
    cp $GITDOT_PATH/gitignore $HOME/.gitignore
}


# Full dotfiles setup
function dotfiles_setup() {
    zshconf_setup
    vimconf_setup
    tmuxconf_setup
    tidyconf_setup
    gitconf_setup
}


# Show usage if no parameter
USAGE_MSG="
usage:
    $0 <command>
commands:
    --setup <target>  install dotfiles
            all
            bash
            zsh
            vim
            tmux
    --fetch           update dotfiles pull from origin master

*WARNING*
THIS PROGRAM DOES NOT SUPPORT RESET
BACKUP YOUR OWN CONFIGURATION FILES TO RESTORE
"

function show_usage() {
    echo "${USAGE_MSG}"
}

if [ "$#" -lt 1 ]
then
    show_usage
    exit
fi

TARGET=""
while [ "$#" -gt 0 ]; do
    case "$1" in
        --setup) TARGET=$2; shift 2 ;;
        --fetch)
            git fetch && git reset --hard origin/master
            shift;
            exit 0;;
        --) shift ;;
        *) echo "invalid command"; exit 1; break;;
    esac
done

# Setup
case $TARGET in
    vim)
        vimconf_setup;
        ;;
    nvim)
        nvimconf_setup;
        ;;
    tmux)
        tmuxconf_setup;
        ;;
    bash)
        bashconf_setup;
        ;;
    zsh)
        zshconf_setup;
        ;;
    git)
        gitconf_setup;
        ;;
    all)
        dotfiles_setup;
        ;;
    *)
        show_usage
        exit 1
        ;;
esac


# vim:ft=sh
