export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

ctags() {
    $(brew --prefix)/bin/ctags "$@"
}

openvpn() {
    $(brew --prefix openvpn)/sbin/openvpn "$@"
}

# rm to rm trash
alias rm="echo Use 'del', or the full path i.e. '/bin/rm'"
alias del="rmtrash"

# Additional git alias
alias gs="git status"

# Docker stuffs
drl() {
    docker rm $(docker ps -a -q -l -f status=exited)
}

dsl() {
    docker stop $(docker ps -lqf status=running)
}

dre() {
    docker rm -v $(docker ps -a -q -f status=exited)
}
alias dim="docker images"
alias drmi="docker rmi"
alias drm="docker rm"
alias dps="docker ps"
alias dpsa="docker ps -a"

alias vim="nvim"
alias vi="nvim"
alias vimdiff="nvim -d"
export EDITOR=/usr/local/bin/nvim

# SSH with remote clipboard alias
ssh-clip() {
    # Send signal directly to netcat when exit to break while loop
    DIRECT_SIG="pbpaste | base64 | nc localhost 7331"
    trap 'eval "${DIRECT_SIG}"' INT TERM EXIT

    REMOTE_SCRIPT="/bin/bash $HOME/.ssh/remote.sh"
    ( eval "$REMOTE_SCRIPT" & ) > /dev/null 2>&1
    ssh -R 1337:localhost:7331 "$@" && eval "${DIRECT_SIG}"
    ( eval "sleep 1 && ${DIRECT_SIG}" & ) > /dev/null 2>&1
}
